//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VaultAtlas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VaultAtlas.resources", typeof(resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total length of the selected {1} shows is approximately {0} hours..
        /// </summary>
        internal static string ApproximatelyXHours {
            get {
                return ResourceManager.GetString("ApproximatelyXHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The artist {0} is already defined. Enter a different name..
        /// </summary>
        internal static string ArtistAlreadyExists {
            get {
                return ResourceManager.GetString("ArtistAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disc (&quot;{1}&quot;) has already been imported under the name &quot;{0}&quot;. Would you like to overwrite the previous import?.
        /// </summary>
        internal static string AskAlreadyPresentVolumeIDOverwrite {
            get {
                return ResourceManager.GetString("AskAlreadyPresentVolumeIDOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the file before closing?.
        /// </summary>
        internal static string AskSaveFileOnExit {
            get {
                return ResourceManager.GetString("AskSaveFileOnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database {
            get {
                object obj = ResourceManager.GetObject("database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_large {
            get {
                object obj = ResourceManager.GetObject("database_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this show?.
        /// </summary>
        internal static string DeleteThisShow {
            get {
                return ResourceManager.GetString("DeleteThisShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This disc number has already been assigned to another disc..
        /// </summary>
        internal static string DiscNumberAlreadyAssigned {
            get {
                return ResourceManager.GetString("DiscNumberAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving file: {0}.
        /// </summary>
        internal static string ErrorWhileSavingFile {
            get {
                return ResourceManager.GetString("ErrorWhileSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file could not be found..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an artist before this show can be entered..
        /// </summary>
        internal static string MustEnterArtistBeforeEnterShow {
            get {
                return ResourceManager.GetString("MustEnterArtistBeforeEnterShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already assigned to another resource..
        /// </summary>
        internal static string NameAlreadyAssignedToResource {
            get {
                return ResourceManager.GetString("NameAlreadyAssignedToResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No drives found..
        /// </summary>
        internal static string NoDrivesAvailable {
            get {
                return ResourceManager.GetString("NoDrivesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no elements for the selected filter..
        /// </summary>
        internal static string NoElementsForFilter {
            get {
                return ResourceManager.GetString("NoElementsForFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more results found..
        /// </summary>
        internal static string NoFurtherOccurrences {
            get {
                return ResourceManager.GetString("NoFurtherOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of the show list..
        /// </summary>
        internal static string NoNextShow {
            get {
                return ResourceManager.GetString("NoNextShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are at the beginning of the show list..
        /// </summary>
        internal static string NoPrevShow {
            get {
                return ResourceManager.GetString("NoPrevShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search reached the end of the table. Do you want to continue searching from the beginning?.
        /// </summary>
        internal static string SearchReachedEnd {
            get {
                return ResourceManager.GetString("SearchReachedEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to import..
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The show has not been saved. Would you like to keep this show?.
        /// </summary>
        internal static string ShowHasNotBeenSaved {
            get {
                return ResourceManager.GetString("ShowHasNotBeenSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusMaster {
            get {
                object obj = ResourceManager.GetObject("StatusMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusPrivate {
            get {
                object obj = ResourceManager.GetObject("StatusPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusReplace {
            get {
                object obj = ResourceManager.GetObject("StatusReplace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusVideo {
            get {
                object obj = ResourceManager.GetObject("StatusVideo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
